### ISSUE TITLE
Migrate to 64bit build

### ISSUE THREAD

**Issue by ensisoft** [ensisoft/newsflash-plus#52]

**Comment by brezn1** [comment]
Any intentions to do the same for Linux?

Reason: Couldn't get it to run under Arch Linux (64bit). Even tried it with a 32-Bit virtualbox ubuntu image.  The software complained about missing libraries. Maybe soft-link errors, maybe 64bit-reasons (i installed multi-arch) In the end it was too tedious to hunt for ghosts. 
But what i know: Your software seems to be one of the last resorts of true usenet-readers for Linux. So  i hope newsflash will take the 64bit jump ;-)

**Comment by ensisoft** [comment]
@brezn1 Yes the Linux releases will also be 64bit.  There's just nothing special to be done for this. In fact all my development already occurs on a 64bit Linux.

**Comment by ensisoft** [comment]
@brezn1 Hi I finally have a new release. Are you still using the software? Any problems?

**Comment by brezn1** [comment]
@ensisoft Works like a charm now. Thanks a bunch!

**Comment by ensisoft** [comment]
@brezn1 good to know! :)
